version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/front" # Ubicaci贸n del directorio que contiene package.json
      schedule:
          interval: "daily"
    - package-ecosystem: "maven"
      directory: "/back_base" # Ubicaci贸n del directorio que contiene pom.xml
      schedule:
          interval: "daily"
    - package-ecosystem: "maven"
      directory: "/back_chat" # Ubicaci贸n del directorio que contiene pom.xml
      schedule:
          interval: "daily"
    - package-ecosystem: "maven"
      directory: "/back_streaming" # Ubicaci贸n del directorio que contiene pom.xml
      schedule:
          interval: "daily"
