{ "id_curso" :3,
"nombre_curso" :"Curso de Libertad Financiera",
"profesores_curso" :[{"id_usuario":1,"nombre_usuario":"Matt I de la Gole®","foto_usuario":["http://localhost:8080/usuario/fotos/roble_texto.svg"],
"presentacion" :"El creador de la Autarquía de la Gole, y el creador de esta plataforma." } ],
"fecha_publicacion_curso" :"2024-08-06T22:00:00.000+00:00",
"clases_curso" :[{"id_clase":7,"nombre_clase":"Clase 1 - Presentación","descriccion_clase":"Presentación del profesor","contenido_clase":"contenido de prueba","tipo_clase":1,"direccion_clase":"http://corso3/clase1","posicion_clase":1},{"id_clase":8,"nombre_clase":"Clase 2 - Las estructuras societarias","descriccion_clase":"Muchas es mejor!!","contenido_clase":null,"tipo_clase":1,"direccion_clase":"http://corso3/clase2","posicion_clase":2},{"id_clase":11,"nombre_clase":"clase de prueba","descriccion_clase":"probando la subida de una nueva clase","contenido_clase":"pontenido de esta prueba","tipo_clase":0,"direccion_clase":"","posicion_clase":3}],
"planes_curso" :[],
"descriccion_corta" :"Aprende las técnicas de ingeniería financiera para dejar de pagar impuestos sobre tu trabajo !!",
"descriccion_larga" :"Cansado de trabajar duro y ganar poco?? Estas harto de pagar impuestos sobre tu trabajo???\n\t\tEste curso es lo que buscas!!!\n\t\tAprenderás las mejores técnicas de ingeniería financiera, como los Fideicomisos, las empresas off-shore y fundaciones.",
"imagen_curso" :"http://localhost:8080/usuario/fotos/roble_texto.svg",
"precio_curso" :70 } { "id_curso" :3,
"nombre_curso" :"Curso de Libertad Financiera",
"profesores_curso" :[{"id_usuario":1,"nombre_usuario":"Matt I de la Gole®","foto_usuario":["http://localhost:8080/usuario/fotos/roble_texto.svg"],
"presentacion" :"El creador de la Autarquía de la Gole, y el creador de esta plataforma." } ],
"fecha_publicacion_curso" :"2024-08-06T22:00:00.000+00:00",
"clases_curso" :[{"id_clase":7,"nombre_clase":"Clase 1 - Presentación","descriccion_clase":"Presentación del profesor","contenido_clase":"contenido de prueba","tipo_clase":1,"direccion_clase":"http://corso3/clase1","posicion_clase":1},{"id_clase":8,"nombre_clase":"Clase 2 - Las estructuras societarias","descriccion_clase":"Muchas es mejor!!","contenido_clase":null,"tipo_clase":1,"direccion_clase":"http://corso3/clase2","posicion_clase":2},{"id_clase":11,"nombre_clase":"clase de prueba","descriccion_clase":"probando la subida de una nueva clase","contenido_clase":"pontenido de esta prueba","tipo_clase":0,"direccion_clase":"","posicion_clase":3}],
"planes_curso" :[],
"descriccion_corta" :"Aprende las técnicas de ingeniería financiera para dejar de pagar impuestos sobre tu trabajo !!",
"descriccion_larga" :"Cansado de trabajar duro y ganar poco?? Estas harto de pagar impuestos sobre tu trabajo???\n\t\tEste curso es lo que buscas!!!\n\t\tAprenderás las mejores técnicas de ingeniería financiera, como los Fideicomisos, las empresas off-shore y fundaciones.",
"imagen_curso" :"http://localhost:8080/usuario/fotos/8feb34be-482a-4608-b7b8-d738ee3f3a63_Usdollar100front.webp",
"precio_curso" :70 }