# Usamos la imagen base de nginx con el módulo RTMP
FROM tiangolo/nginx-rtmp

# RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN sed -i 's/listen 1935;/listen 8060;/' /etc/nginx/nginx.conf

# Exponemos los puertos 8060 para RTMP y 8050 para HTTP
EXPOSE 8060

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]
